import { expect, test } from 'bun:test';
import { discoverDemos, renderDemoSourceMap, renderRegistry } from './generate-demo-registry.js';

test('discovers a preview-backed Unstyled demo and renders its registry entry', () => {
  const demos = discoverDemos([
    {
      file: 'ButtonDemo.kt',
      source: `package com.composeunstyled.demo

import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview

@Preview
@UnstyledDemo("button")
@Composable
fun ButtonDemo() = Unit
`,
    },
  ]);

  expect(demos).toEqual([
    {
      id: 'button',
      title: undefined,
      section: 'Components',
      contentAlignment: 'Center',
      padding: 'Default',
      name: 'ButtonDemo',
      packageName: 'com.composeunstyled.demo',
      file: 'ButtonDemo.kt',
    },
  ]);
  expect(renderRegistry(demos)).toContain(
    'section = DemoSection.Components',
  );
  expect(renderDemoSourceMap(demos)).toBe(
    '# Generated by scripts/generate-demo-registry.js. Do not edit.\nbutton=demo/src/commonMain/kotlin/ButtonDemo.kt\n',
  );
});

test('rejects duplicate demo ids', () => {
  const source = id => `package com.composeunstyled.demo

import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview

@Preview
@UnstyledDemo("${id}")
@Composable
fun ${id.replace('-', '_')}Demo() = Unit
`;

  expect(() => discoverDemos([
    { file: 'FirstDemo.kt', source: source('button') },
    { file: 'SecondDemo.kt', source: source('button') },
  ])).toThrow('duplicate demo id: button');
});

test('rejects a demo without an IDE preview', () => {
  expect(() => discoverDemos([
    {
      file: 'ButtonDemo.kt',
      source: `package com.composeunstyled.demo

import androidx.compose.runtime.Composable

@UnstyledDemo("button")
@Composable
fun ButtonDemo() = Unit
`,
    },
  ])).toThrow('@UnstyledDemo requires @Preview');
});
