name: Redeploy documentation

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/deploy-website.yml
